### ISSUE TITLE
Issue that is unrelated to the repository

### ISSUE THREAD

**Issue by vhcrack** [WorldEditAxe/your-mom-rpc#1]
I can't seem to find a way to contact you on your github profile, I tried your discord tag (q13x#0001) but it didn't work. Do you have a way for me to easily contact you?

**Comment by vhcrack** [comment]
Praying that you see this eventually lmfao

**Comment by dxomg** [comment]
He prob never will lmao

**Comment by vhcrack** [comment]
> He prob never will lmao

I did manage to get his discord, it was later on his eaglerproxy repo though

**Comment by WorldEditAxe** [comment]
> He prob never will lmao

yeah man I never got to him 😔
